version: "3.7"
services:
  api:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017